services:
  - type: web
    name: cana-ml
    env: python
    pythonVersion: "3.10.12"

    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt

    startCommand: >
      gunicorn app:app
      --workers 1
      --timeout 120
      --preload
      --bind 0.0.0.0:$PORT

    disks:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 1

