services:
  - type: web
    name: cana-ml
    env: python
    pythonVersion: "3.10.12"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    disks:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 1
      - name: recent
        mountPath: /app/static/recent
        sizeGB: 1
